#!/usr/bin/env python3
"""Check the member paths in the wheel and sdist that will be published.

The sdist roots below freeze the existing source-distribution contract:
setuptools' project files and generated metadata, the product package, and
the three MANIFEST.in grafts. Changing package discovery or adding a VCS file
finder must not silently widen this boundary. This check reads archives;
it neither extracts them nor trusts the packaging configuration.
"""

from __future__ import annotations

from email.parser import BytesParser
from pathlib import Path
import re
import stat
import sys
import tarfile
from typing import List, Optional, Tuple
import zipfile


PROJECT_NAME = "session-preserve"
PACKAGE_NAME = "codex_preserve"
SDIST_ROOT_FILES = frozenset({
    "LICENSE", "MANIFEST.in", "PKG-INFO", "README.md", "pyproject.toml",
    "setup.cfg",  # generated by setuptools when building the sdist
})
SDIST_GRAFT_DIRS = frozenset({"tests", "examples", "tools"})
EGG_INFO_FILES = frozenset({
    "PKG-INFO", "SOURCES.txt", "dependency_links.txt", "entry_points.txt",
    "top_level.txt",
})


class DistributionError(ValueError):
    """The built distribution violates the product boundary."""


def _parts(name: str) -> Tuple[str, ...]:
    # Check the raw archive name before any path library can normalize it.
    value = name[:-1] if name.endswith("/") else name
    parts = tuple(value.split("/"))
    if (not value or "\\" in value or ":" in value
            or any(part in ("", ".", "..") for part in parts)):
        raise DistributionError("unsafe archive member: %r" % name)
    if any("contextbridge" in part.casefold() for part in parts):
        raise DistributionError("forbidden sibling-product member: %r" % name)
    return parts


def _normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _metadata(data: bytes) -> Tuple[str, str]:
    message = BytesParser().parsebytes(data)
    names = message.get_all("Name", [])
    versions = message.get_all("Version", [])
    if len(names) != 1 or _normalize_name(names[0]) != PROJECT_NAME:
        raise DistributionError("metadata must name only %s" % PROJECT_NAME)
    if (len(versions) != 1
            or not re.fullmatch(r"[0-9][A-Za-z0-9.!+_]*", versions[0])):
        raise DistributionError("missing or unsafe metadata version")
    return PROJECT_NAME, versions[0]


def _top_level(data: bytes) -> None:
    try:
        roots = data.decode("utf-8").split()
    except UnicodeDecodeError as error:
        raise DistributionError("top_level.txt is not UTF-8") from error
    if roots != [PACKAGE_NAME]:
        raise DistributionError("top_level.txt must name only %s" % PACKAGE_NAME)


def check_wheel(path: Path) -> Tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        members = archive.infolist()
        names = [item.filename for item in members]
        if len(names) != len(set(names)):
            raise DistributionError("duplicate wheel members")
        parts = {name: _parts(name) for name in names}
        metadata = [name for name, pieces in parts.items()
                    if len(pieces) == 2 and pieces[0].endswith(".dist-info")
                    and pieces[1] == "METADATA"]
        if len(metadata) != 1:
            raise DistributionError("wheel must contain exactly one METADATA")
        identity = _metadata(archive.read(metadata[0]))
        expected = "%s-%s.dist-info" % (identity[0].replace("-", "_"),
                                        identity[1])
        for member in members:
            pieces = parts[member.filename]
            if pieces[0] not in (PACKAGE_NAME, expected) or "apps" in pieces:
                raise DistributionError("wheel member outside product: %r"
                                        % member.filename)
            if len(pieces) == 1 and not member.is_dir():
                raise DistributionError("wheel product root is not a directory")
            kind = stat.S_IFMT(member.external_attr >> 16)
            if kind not in (0, stat.S_IFREG, stat.S_IFDIR):
                raise DistributionError("wheel contains a special file: %r"
                                        % member.filename)
            if pieces == (expected, "top_level.txt"):
                _top_level(archive.read(member))
        return identity


def _sdist_allowed(pieces: Tuple[str, ...], is_dir: bool) -> bool:
    if not pieces:
        return is_dir
    if len(pieces) == 1 and pieces[0] in SDIST_ROOT_FILES:
        return not is_dir
    if pieces[0] in SDIST_GRAFT_DIRS:
        return len(pieces) > 1 or is_dir
    if pieces[0] != "src":
        return False
    if len(pieces) == 1:
        return is_dir
    if pieces[1] == PACKAGE_NAME:
        return len(pieces) > 2 or is_dir
    if pieces[1] == PROJECT_NAME.replace("-", "_") + ".egg-info":
        return ((len(pieces) == 2 and is_dir)
                or (len(pieces) == 3 and not is_dir
                    and pieces[2] in EGG_INFO_FILES))
    return False


def check_sdist(path: Path) -> Tuple[str, str]:
    with tarfile.open(path, "r:gz") as archive:
        members = archive.getmembers()
        names = [item.name for item in members]
        if len(names) != len(set(names)):
            raise DistributionError("duplicate sdist members")
        parts = {name: _parts(name) for name in names}
        roots = {pieces[0] for pieces in parts.values()}
        if len(roots) != 1:
            raise DistributionError("sdist must have one leading project directory")
        root = roots.pop()
        metadata = [item for item in members
                    if parts[item.name] == (root, "PKG-INFO") and item.isfile()]
        if len(metadata) != 1:
            raise DistributionError("sdist must contain one root PKG-INFO")
        with archive.extractfile(metadata[0]) as stream:
            identity = _metadata(stream.read())
        suffix = "-" + identity[1]
        if (not root.endswith(suffix)
                or _normalize_name(root[:-len(suffix)]) != identity[0]):
            raise DistributionError("sdist root disagrees with its metadata")
        for member in members:
            pieces = parts[member.name][1:]
            if not member.isdir() and not member.isfile():
                raise DistributionError("sdist contains a special file: %r"
                                        % member.name)
            if not _sdist_allowed(pieces, member.isdir()):
                raise DistributionError("sdist member outside frozen allowlist: %r"
                                        % member.name)
            if pieces == ("src", "session_preserve.egg-info", "top_level.txt"):
                with archive.extractfile(member) as stream:
                    _top_level(stream.read())
        return identity


def main(argv: Optional[List[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    wheels = [Path(name) for name in args if name.endswith(".whl")]
    sdists = [Path(name) for name in args if name.endswith(".tar.gz")]
    if len(args) != 2 or len(wheels) != 1 or len(sdists) != 1:
        print("DISTRIBUTION_CONTENT=FAIL: supply exactly one wheel and one sdist")
        return 1
    try:
        wheel_identity = check_wheel(wheels[0])
        sdist_identity = check_sdist(sdists[0])
        if wheel_identity != sdist_identity:
            raise DistributionError("wheel and sdist metadata disagree")
    except (DistributionError, OSError, ValueError, tarfile.TarError,
            zipfile.BadZipFile) as error:
        print("DISTRIBUTION_CONTENT=FAIL: %s" % error)
        return 1
    print("DISTRIBUTION_CONTENT=PASS: %s %s" % wheel_identity)
    return 0


if __name__ == "__main__":
    sys.exit(main())
